import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";
import LogoutLogin from "./components/dynamicLogs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Boardgame App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <div className="flex items-right justify-center">
          {/* <LogoutLogin /> */}
          <button>
            <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" href={'/'}>Home</Link>
          </button>
          <button>
            <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" href={'/profile'}>Profile</Link>
          </button>
          <button>
            <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" href={'/games'}>Games</Link>
          </button>
          <button>
            <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" href={'/reviews'}>Reviews</Link>
          </button>
        </div>
        {children}
      </body>
    </html>
  );
}
