import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Boardgame App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <div className="flex items-right justify-center">
          <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" style={{ color: "var(--bums-dark-blue)" }} href={'/login'}>Login</Link>
          <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" style={{ color: "var(--bums-dark-blue)" }} href={'/signup'}>Sign Up</Link>
          <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" style={{ color: "var(--bums-dark-blue)" }} href={'/'}>Home</Link>
          <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" style={{ color: "var(--bums-dark-blue)" }} href={'/profile'}>Profile</Link>
          <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" style={{ color: "var(--bums-dark-blue)" }} href={'/games'}>Games</Link>
          <Link className="flex-col items-right justify-center p-1 m-2 bg-white-300" style={{ color: "var(--bums-dark-blue)" }} href={'/reviews'}>Reviews</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
